export default {
  appName: 'Muskz Command',
  common: {
    loading: 'SİSTEM YÜKLENİYOR...',
    error: 'SİSTEM HATASI',
    unknown: 'BİLİNMEYEN BİRİM',
    notAvailable: 'N/A',
    openMenu: 'PANELİ AÇ',
  },
  status: {
    checking: 'SİSTEM DURUMU DENETLENİYOR...',
    running: 'ANTIGRAVITY MOTORU AKTİF',
    stopped: 'ANTIGRAVITY MOTORU ÇEVRİMDIŞI',
  },
  action: {
    stop: 'DURDUR',
    start: 'BAŞLAT',
    switch: 'GEÇİŞ YAP',
    deleteBackup: 'YEDEĞİ İMHA ET',
    backupCurrent: 'GÜNCEL DURUMU YEDEKLE',
    retry: 'YENİDEN DENE',
    openLogs: 'LOG DİZİNİNİ AÇ',
  },
  error: {
    generic: 'BEKLENMEYEN BİR SİSTEM HATASI OLUŞTU.',
    keychainUnavailable: 'GÜVENLİK ANAHTARI (KEYCHAIN) ERİŞİLEMEZ DURUMDA.',
    keychainHint: {
      translocation:
        'MACOS APP TRANSLOCATION TESPİT EDİLDİ. UYGULAMAYI /APPLICATIONS DİZİNİNE TAŞIYIP YENİDEN BAŞLATIN.',
      keychainDenied:
        'GÜVENLİK ANAHTARI ERİŞİMİ REDDEDİLDİ. UYGULAMA İMZASIZ OLABİLİR; SELF-SIGN ÇÖZÜMÜ İÇİN README DOSYASINI İNCELEYİN.',
      signNotarize: 'LÜTFEN MÜMKÜNSE İMZALI VE ONAYLI BİR DERLEME KULLANIN.',
    },
    dataMigrationFailed: 'ESKİ SÜRÜM HESAP VERİSİ ŞİFRELEMESİ ÇÖZÜLEMEDİ.',
    dataMigrationHint: {
      relogin: 'LÜTFEN YENİDEN GİRİŞ YAPIN VEYA SİSTEM DÜĞÜMLERİNİ TEKRAR EKLEYİN.',
      clearData: 'SORUN DEVAM EDERSE, YEREL VERİLERİ TEMİZLEYİP YENİDEN OTURUM AÇIN.',
    },
  },
  nav: {
    accounts: 'YÖNETİM PANELİ',
    proxy: 'AĞ OPERASYON KONSOLU',
    settings: 'DONANIM & KONFİGÜRASYON',
  },
  account: {
    current: 'AKTİF DÜĞÜM',
    lastUsed: 'SON ETKİLEŞİM {{time}}',
  },
  home: {
    title: 'SİSTEM DÜĞÜMLERİ',
    description: 'ANTIGRAVITY GOOGLE GEMINI DÜĞÜM HAVUZUNU YÖNET.',
    noBackups: {
      title: 'YEDEKLEME BULUNAMADI',
      description: 'SİSTEMİ BAŞLATMAK İÇİN MEVCUT ANTIGRAVITY DÜĞÜMÜNÜN BİR YEDEĞİNİ OLUŞTURUN.',
      action: 'GÜNCEL DÜĞÜMÜ YEDEKLE',
    },
  },
  settings: {
    title: 'KONFİGÜRASYON',
    description: 'SİSTEM DONANIM VE TERCİHLERİNİ YAPIKLANDIR.',
    general: 'TEMEL AYARLAR',
    connection: 'BAĞLANTI AĞI',
    models: 'YAPAY ZEKA MODELLERİ',
    appearance: {
      title: 'ARAYÜZ',
      description: 'MUSKZ COMMAND GÖRSEL DONANIMINI KİŞİSELLEŞTİR.',
    },
    darkMode: 'KARANLIK MOD',
    darkModeDescription: 'GECE OPERASYONLARI İÇİN OPTİMİZE EDİLMİŞ ARAYÜZÜ AKTİF ET.',
    language: {
      title: 'SİSTEM DİLİ',
      description: 'OPERASYON DİLİNİ SEÇİN.',
      english: 'İNGİLİZCE (EN)',
      chinese: 'ÇİNCE (ZH-CN)',
      russian: 'RUSÇA (RU)',
      vietnamese: 'VİETNAMCA (VI)',
      turkish: 'TÜRKÇE (TR)',
    },
    about: {
      title: 'SİSTEM BİLGİSİ',
      description: 'DONANIM VE YAZILIM VERSİYON VERİLERİ.',
    },
    version: 'SÜRÜM',
    platform: 'PLATFORM',
    license: 'LİSANS',
    openLogDir: 'ERİŞİM SAĞLA',
    toast: {
      saved: {
        title: 'KONFİGÜRASYON KAYDEDİLDİ',
        description: 'SİSTEM TERCİHLERİ GÜNCELLENDİ.',
      },
      saveFailed: {
        title: 'KONFİGÜRASYON KAYIT HATASI',
      },
    },
    account: {
      title: 'DÜĞÜM PARAMETRELERİ',
      description: 'OTOMATİK SENKRONİZASYON VE KOTA DENETİMİNİ YAPILANDIR.',
      auto_refresh: 'OTOMATİK KOTA TARAMASI',
      auto_refresh_desc: 'TÜM DÜĞÜMLER İÇİN KOTA VERİSİNİ PERİYODİK OLARAK SORGULA',
      auto_sync: 'AKTİF DÜĞÜMÜ SENKRONİZE ET',
      auto_sync_desc: 'AKTİF DÜĞÜM VERİSİNİ PERİYODİK OLARAK GÜNCELLE',
    },
    startup: {
      title: 'BAŞLANGIÇ PROTOKOLÜ',
      description: 'SİSTEM BAŞLATILIRKEN UYGULANACAK OTOMATİK EYLEMLER.',
      auto_startup: 'SİSTEMLE BERABER BAŞLAT',
      auto_startup_desc: 'OTURUM AÇILDIĞINDA ÇEKİRDEK SERVİSİ ARKA PLANDA ÇALIŞTIR',
      macos_hint:
        'MACOS İÇİN BAŞLANGIÇ ÖĞELERİNİN ÇALIŞMASI İÇİN UYGULAMANIN İMZALI OLMASI GEREKİR. BAŞARISIZ OLURSA, SİSTEM AYARLARINDAN MANUEL OLARAK ETKİNLEŞTİRİN.',
    },
    privacy: {
      title: 'GİZLİLİK VE GÜVENLİK',
      description: 'TELEMETRİ VE HATA RAPORLAMA AYARLARI.',
      error_reporting: 'HATA RAPORLAMASI',
      error_reporting_desc:
        'GELİŞTİRME SÜRECİNE DESTEK OLMAK İÇİN ANONİM ÇÖKME VERİLERİNİ GÖNDER. KİŞİSEL VERİ TOPLANMAZ.',
      restart_note: 'HATA RAPORLAMA DEĞİŞİKLİKLERİ SİSTEM YENİDEN BAŞLATILDIKTAN SONRA AKTİF OLUR.',
    },
    notifications: {
      title: 'BİLDİRİM SİSTEMİ',
      description: 'SİSTEM OLAYLARI İÇİN MASAÜSTÜ UYARILARINI YAPILANDIR.',
      quotaAlert: 'DÜŞÜK KOTA UYARISI',
      quotaAlertDesc: 'BİR MODELİN KOTASI BELİRLENEN EŞİĞİN ALTINA DÜŞTÜĞÜNDE BİLDİRİM AL',
      quotaThreshold: 'KRİTİK EŞİK SEVİYESİ',
      quotaThresholdDesc: 'UYARIYI TETİKLEYECEK YÜZDE ORANI',
      saveFailed: 'BİLDİRİM AYARLARI KAYDEDİLEMEDİ',
      thresholdSaveFailed: 'EŞİK DEĞERİ KAYDEDİLEMEDİ',
    },
    proxy: {
      title: 'UPSTREAM PROXY AĞI',
      description: 'GOOGLE/GEMINI API İSTEKLERİ İÇİN YÖNLENDİRİCİ AĞ YAPILANDIRMASI.',
      enable: 'UPSTREAM PROXY ETKİN',
      url: 'PROXY BAĞLANTI ADRESİ',
      timeout: 'İSTEK ZAMAN AŞIMI (SANİYE)',
    },
    modelMapping: {
      title: 'MODEL YÖNLENDİRME HARİTASI',
      description:
        'CLAUDE CODE MODELLERİNİ ANTIGRAVITY MODELLERİNE HARİTALANDIR. MALİYET VE HIZ OPTİMİZASYONU İÇİN AKILLI YÖNLENDİRME YAP.',
      claudeKeyword: 'CLAUDE MODELİ (ANAHTAR KELİME)',
      targetGemini: 'HEDEF GEMINI MODELİ',
      addPlaceholderKey: 'ÖRNEK: op-3',
      addPlaceholderValue: 'ÖRNEK: gemini-3-flash',
      noMappings: 'ÖZEL YÖNLENDİRME TANIMLANMADI.',
      mapsTo: 'YÖNLENDİRİLEN:',
      default: 'VARSAYILAN',
      restoreDefaults: 'VARSAYILANLARA SIFIRLA',
    },
    modelVisibility: {
      title: 'MODEL GÖRÜNÜRLÜK FİLTRESİ',
      description:
        'SİSTEM DÜĞÜM KARTLARINDA HANGİ MODELLERİN GÖSTERİLECEĞİNİ KONTROL ET. GİZLENEN MODELLER KOTA EKRANINDA YER ALMAZ.',
      searchPlaceholder: 'MODEL ARA...',
      showAll: 'TÜMÜNÜ GÖSTER',
      hideAll: 'TÜMÜNÜ GİZLE',
      reset: 'FABRİKA AYARLARINA DÖN',
      save: 'KONFİGÜRASYONU KAYDET',
      noModels: 'MODEL BULUNAMADI',
      modelsShown: '{{total}} MODELDEN {{visible}} TANESİ AKTİF',
      quotaManagement: 'KOTA YÖNETİM MERKEZİ',
      hidden: 'GİZLİ',
      noModelsFound: 'EŞLEŞEN MODEL YOK',
      totalModels: 'TOPLAM',
      visibleModels: 'AKTİF',
      hiddenModels: 'GİZLİ',
      saving: 'KAYDEDİLİYOR...',
    },
    providerGroupings: {
      title: 'SAĞLAYICI KÜMELEMESİ',
      description: 'DAHA İYİ ORGANİZASYON İÇİN MODELLERİ SAĞLAYICILARINA GÖRE GRUPLANDIR',
      enabled: 'SAĞLAYICI KÜMELEMESİNİ AKTİF ET',
      models: '{{count}} MODEL',
      avgLabel: 'ORT',
      resetLabel: 'SIFIRLA',
      overall: 'GENEL DURUM',
      healthy: 'STABİL',
      degraded: 'VERİMSİZ',
      limited: 'KISTILANMIŞ',
      critical: 'KRİTİK',
    },
    examples: {
      title: 'KULLANIM PROTOKOLLERİ',
      description: 'YEREL API PROXY İÇİN ÖRNEK ÇAĞRI KOMUTLARI.',
      curl: 'CURL',
      python: 'PYTHON',
      copy: 'KOPYALA',
      copied: 'KOPYALANDI!',
      openai_protocol: 'OPENAI PROTOKOLÜ',
      anthropic_protocol: 'ANTHROPIC PROTOKOLÜ',
      openai_tools: 'CURSOR, WINDSURF, NEXTCHAT',
      anthropic_tools: 'CLAUDE CODE CLI',
      flash: 'HIZLI (FLASH)',
      pro: 'GELİŞMİŞ (PRO)',
      flash_preview: 'ÖNİZLEME (PREVIEW)',
      pro_high: 'MAKSİMUM GÜÇ',
      sonnet: 'DÜŞÜNEN (THINKING)',
      opus: 'OPUS',
    },
    gateway: {
      title: 'API PROXY SERVİSİ',
      description: 'YEREL API YÖNLENDİRİCİSİNİ KONTROL ET.',
      status_running: 'AKTİF',
      status_stopped: 'ÇEVRİMDIŞI',
      action_start: 'SERVİSİ BAŞLAT',
      action_stop: 'SERVİSİ DURDUR',
      accounts_info: '{{count}} DÜĞÜM OPERASYONEL',
      port: 'DİNLEME PORTU',
      port_hint: 'VARSAYILAN 8045, DEĞİŞİKLİKLER İÇİN SİSTEM YENİDEN BAŞLATILMALIDIR',
      timeout: 'İSTEK ZAMAN AŞIMI',
      timeout_hint: 'VARSAYILAN 120S, LİMİT 30-600S',
      api_key: 'GÜVENLİK ANAHTARI (API KEY)',
      regenerate_key: 'YENİDEN OLUŞTUR',
      regenerateConfirm: {
        title: 'GÜVENLİK ANAHTARINI SIFIRLA?',
        description:
          'BU İŞLEM MEVCUT API ANAHTARINI ANINDA GEÇERSİZ KILAR. ESKİ ANAHTARI KULLANAN TÜM UYGULAMALARIN BAĞLANTISI KESİLECEKTİR.',
        cancel: 'İPTAL ET',
        confirm: 'SIFIRLA',
      },
      key_warning: 'API ANAHTARINIZI GÜVENDE TUTUN. YETKİSİZ ERİŞİME İZİN VERMEYİN.',
      auto_start: 'SİSTEMLE OTOMATİK BAŞLAT',
      auto_start_desc: 'UYGULAMA ÇALIŞTIĞINDA PROXY SERVİSİNİ OTOMATİK TETİKLE',
    },
    proxy_tab: 'PROXY AĞI',
    save: 'KONFİGÜRASYONU UYGULA',
  },
  toast: {
    backupSuccess: {
      title: 'BAŞARILI',
      description: 'DÜĞÜM YEDEĞİ OLUŞTURULDU.',
    },
    backupError: {
      title: 'KRİTİK HATA',
      description: 'YEDEK OLUŞTURULAMADI: {{error}}',
    },
    switchSuccess: {
      title: 'BAŞARILI',
      description: 'DÜĞÜM GEÇİŞİ TAMAMLANDI.',
    },
    switchError: {
      title: 'KRİTİK HATA',
      description: 'DÜĞÜM DEĞİŞTİRİLEMEDİ: {{error}}',
    },
    deleteSuccess: {
      title: 'BAŞARILI',
      description: 'DÜĞÜM YEDEĞİ İMHA EDİLDİ.',
    },
    deleteError: {
      title: 'KRİTİK HATA',
      description: 'YEDEK SİLİNEMEDİ: {{error}}',
    },
  },
  cloud: {
    title: 'SİSTEM DÜĞÜMLERİ',
    description: 'GOOGLE GEMINI DÜĞÜM HAVUZUNU YÖNET.',
    autoSwitch: 'OTONOM YÖNLENDİRME',
    providerGroupings: 'SAĞLAYICI GRUPLAMASI',
    addAccount: 'YENİ DÜĞÜM EKLE',
    syncFromIDE: 'IDE ÜZERİNDEN SENKRONİZE ET',
    checkQuota: 'KOTA DENETİMİNİ BAŞLAT',
    polling: 'SİSTEM TARAMASI BAŞLATILDI',
    globalQuota: 'GENEL KAPASİTE',
    layout: {
      auto: 'OTOMATİK',
      twoCol: '2 SÜTUN',
      threeCol: '3 SÜTUN',
      list: 'LİSTE GÖRÜNÜMÜ',
      compact: 'KOMPAKT MOD',
    },
    authDialog: {
      title: 'GOOGLE HESABI ENTEGRASYONU',
      description: 'SİSTEME DÜĞÜM EKLEMEK İÇİN YETKİLENDİRME GEREKİYOR.',
      oauthClient: 'OAUTH İSTEMCİSİ',
      oauthClientPlaceholder: 'OAUTH İSTEMCİSİNİ SEÇİN',
      openLogin: 'GİRİŞ PANELİNİ AÇ',
      authCode: 'YETKİLENDİRME KODU',
      placeholder: '4/ İLE BAŞLAYAN KODU GİRİN...',
      instruction:
        'GOOGLE GİRİŞİ İÇİN VARSAYILAN TARAYICIYI AÇACAKTIR. LOCALHOST SAYFASINDAKİ KODU KOPYALAYIP BURAYA YAPIŞTIRIN.',
      verify: 'DOĞRULA VE SİSTEME EKLE',
    },
    card: {
      active: 'AKTİF',
      use: 'ETKİNLEŞTİR',
      rateLimited: 'LİMİTLENDİ',
      validationRiskControlled: 'RİSK / LİMİTLENDİ',
      validationOAuthReauthRequired: 'OAUTH YENİDEN YETKİLENDİRME',
      validationRequired: 'DOĞRULAMA GEREKİYOR',
      left: 'KALAN',
      used: 'KULLANILAN',
      unknown: 'BİLİNMEYEN KİMLİK',
      actions: 'OPERASYONLAR',
      useAccount: 'DÜĞÜMÜ KULLAN',
      identityProfile: 'KİMLİK PROFİLİ',
      refresh: 'KOTAYI SORGULA',
      delete: 'DÜĞÜMÜ İMHA ET',
      noQuota: 'KOTA VERİSİ YOK',
      rateLimitedQuota: 'LİMİT AŞILDI',
      resetPrefix: 'SIFIRLANMA',
      resetTime: 'SIFIRLANMA ZAMANI',
      resetUnknown: 'BİLİNMİYOR',
      gemini3Ready: 'GEMINI 3 HAZIR',
      groupGoogleGemini: 'GOOGLE GEMINI AĞI',
      groupAnthropicClaude: 'ANTHROPIC CLAUDE AĞI',
      proxy: 'PROXY BAĞLANTISI',
      proxyPlaceholder: 'ÖRN: http://127.0.0.1:7890',
      proxySaved: 'PROXY KAYDEDİLDİ',
      noProxy: 'PROXY YOK',
      aiCredits: 'YAPAY ZEKA KREDİSİ',
      aiCreditsValue: '{{amount}} KREDİ',
      creditsExpiry: 'SON KULLANMA: {{date}}',
      modelVisibility: 'MODEL GÖRÜNÜRLÜĞÜ',
    },
    identity: {
      title: 'KİMLİK PROFİLİ',
      loading: 'VERİLER İNDİRİLİYOR...',
      generateAndBind: 'OLUŞTUR VE BAĞLA',
      captureAndBind: 'MEVCUT OLANI YAKALA VE BAĞLA',
      restoreOriginal: 'TEMEL PROFİLE DÖN',
      openFolder: 'KİMLİK DEPOSUNU AÇ',
      previewTitle: 'OLUŞTURULAN KİMLİK ÖNİZLEMESİ',
      confirm: 'ONAYLA',
      cancel: 'İPTAL ET',
      close: 'KAPAT',
      currentStorage: 'AKTİF ÇALIŞMA KİMLİĞİ',
      accountBinding: 'BAĞLI DÜĞÜM KİMLİĞİ',
      history: 'KİMLİK GEÇMİŞİ',
      noHistory: 'KİMLİK KAYDI BULUNAMADI',
      current: 'AKTİF',
      restore: 'GERİ YÜKLE',
      generateSuccess: 'YENİ KİMLİK OLUŞTURULDU VE BAĞLANDI',
      captureSuccess: 'MEVCUT KİMLİK KAYDEDİLDİ VE BAĞLANDI',
      restoreOriginalSuccess: 'TEMEL KİMLİK GERİ YÜKLENDİ',
      restoreVersionSuccess: 'TARİHSEL KİMLİK GERİ YÜKLENDİ',
      deleteVersionSuccess: 'TARİHSEL KİMLİK SİLİNDİ',
      openFolderSuccess: 'KİMLİK DEPOSU ERİŞİME AÇILDI',
      baseline: 'TEMEL KİMLİK',
    },
    list: {
      noAccounts: 'SİSTEME HENÜZ HİÇBİR DÜĞÜM EKLENMEDİ.',
    },
    error: {
      loadFailed: 'BULUT DÜĞÜMLERİ YÜKLENEMEDİ.',
    },
    toast: {
      syncSuccess: {
        title: 'SENKRONİZASYON BAŞARILI',
        description: 'IDE ÜZERİNDEN {{email}} İÇE AKTARILDI.',
      },
      syncFailed: {
        title: 'SENKRONİZASYON HATASI',
        description: 'IDE VERİTABANINDA AKTİF BİR DÜĞÜM BULUNAMADI.',
      },
      addSuccess: 'DÜĞÜM SİSTEME BAŞARIYLA ENTEGRE EDİLDİ!',
      addFailed: {
        title: 'DÜĞÜM EKLENEMEDİ',
      },
      quotaRefreshed: 'KOTA VERİSİ GÜNCELLENDİ',
      refreshFailed: 'KOTA SORGULANAMADI',
      pollFailed: 'TÜM DÜĞÜMLER İÇİN KOTA TARAMASI BAŞARISIZ OLDU',
      switched: {
        title: 'DÜĞÜM AKTİF EDİLDİ!',
        description: 'ANTIGRAVITY MOTORU YENİDEN BAŞLATILIYOR...',
      },
      switchFailed: 'DÜĞÜM DEĞİŞTİRME İŞLEMİ BAŞARISIZ',
      deleted: 'DÜĞÜM SİSTEMDEN SİLİNDİ',
      deleteFailed: 'DÜĞÜM SİLİNEMEDİ',
      deleteConfirm: 'BU DÜĞÜMÜ SİSTEMDEN KALICI OLARAK SİLMEK İSTEDİĞİNİZE EMİN MİSİNİZ?',
      autoSwitchOn: 'OTONOM YÖNLENDİRME AKTİF EDİLDİ',
      autoSwitchOff: 'OTONOM YÖNLENDİRME DEVRE DIŞI BIRAKILDI',
      updateSettingsFailed: 'KONFİGÜRASYON GÜNCELLENEMEDİ',
      actionFailed: 'OPERASYON BAŞARISIZ',
      startAuthFailed: 'KİMLİK DOĞRULAMA AKIŞI BAŞLATILAMADI',
      refreshCreditsAvailable: 'YAPAY ZEKA KREDİSİ: {{amount}}',
      refreshCreditsUnavailable: 'BU YENİLEME İÇİN YAPAY ZEKA KREDİSİ KULLANILAMIYOR.',
      batchRefreshSuccess: '{{count}} DÜĞÜM BAŞARIYLA SORGULANDI.',
      batchRefreshPartial: {
        title: 'SORGULAMA EKSİK TAMAMLANDI',
        description: '{{successful}} DÜĞÜM SORGULANDI, {{failed}} DÜĞÜM BAŞARISIZ OLDU.',
      },
      batchDeleteSuccess: '{{count}} DÜĞÜM BAŞARIYLA SİLİNDİ.',
      batchDeletePartial: {
        title: 'SİLME İŞLEMİ EKSİK TAMAMLANDI',
        description: '{{successful}} DÜĞÜM SİLİNDİ, {{failed}} DÜĞÜM BAŞARISIZ OLDU.',
      },
    },
    batch: {
      selected: '{{count}} BİRİM SEÇİLDİ',
      delete: 'SEÇİLENLERİ İMHA ET',
      refresh: 'SEÇİLENLERİ SORGULA',
      selectAll: 'TÜMÜNÜ SEÇ',
      clear: 'SEÇİMİ TEMİZLE',
      confirmDelete: '{{count}} DÜĞÜMÜ SİLMEK İSTEDİĞİNİZE EMİN MİSİNİZ?',
    },
    sort: {
      recentlyUsed: 'SON ETKİLEŞİM',
      quotaOverall: 'GENEL KOTA',
      quotaClaude: 'CLAUDE KOTASI',
      quotaPro3: 'PRO 3 KOTASI',
      quotaFlash: 'FLASH KOTASI',
    },
    exportImport: {
      export: 'DIŞA AKTAR',
      import: 'İÇE AKTAR',
      exportTitle: 'DÜĞÜMLERİ DIŞA AKTAR',
      exportDesc: 'DIŞA AKTARIM DOSYASINA YETKİLENDİRME TOKEN\'LARININ DAHİL EDİLİP EDİLMEYECEĞİNİ SEÇİN.',
      includeTokens: 'TOKEN\'LARI DAHİL ET (GÜVENLİK RİSKİ OLUŞTURABİLİR)',
      stripTokens: 'TOKEN\'LARI TEMİZLE (PAYLAŞIM İÇİN DAHA GÜVENLİ)',
      exportSuccess: 'DÜĞÜMLER BAŞARIYLA DIŞA AKTARILDI',
      importTitle: 'DÜĞÜMLERİ İÇE AKTAR',
      importDesc: 'ÖNCEDEN DIŞA AKTARILMIŞ BİR JSON DOSYASI SEÇİN.',
      importStrategy: 'İÇE AKTARMA STRATEJİSİ',
      strategyMerge: 'BİRLEŞTİR - MEVCUTLARI GÜNCELLE, YENİLERİ EKLE',
      strategyOverwrite: 'ÜZERİNE YAZ - TÜM MEVCUT VERİLERİ DEĞİŞTİR',
      strategySkip: 'ATLA - SADECE YENİ DÜĞÜMLERİ EKLE',
      importSuccess: '{{imported}} EKLENDİ, {{updated}} GÜNCELLENDİ, {{skipped}} ATLANDI',
      importErrors: 'İÇE AKTARMA İŞLEMİ {{count}} HATA İLE TAMAMLANDI',
      selectFile: 'DOSYA SEÇ',
      importing: 'SİSTEME İŞLENİYOR...',
      fileTooLarge: 'DOSYA BOYUTU 5MB LİMİTİNİ AŞIYOR',
      invalidJson: 'GEÇERSİZ JSON FORMATI',
      readFileFailed: 'DOSYA OKUNAMADI',
    },
  },
  proxy: {
    title: 'API AĞ KONSOLU',
    description: 'YEREL API PROXY SERVİSİNİ YÖNET.',
    save: 'KONFİGÜRASYONU UYGULA',
    copy: 'KOPYALA',
    copied: 'KOPYALANDI!',
    regenerate: 'YENİDEN OLUŞTUR',
    regenerateConfirm: {
      title: 'GÜVENLİK ANAHTARINI SIFIRLA?',
      description:
        'BU İŞLEM MEVCUT API ANAHTARINI ANINDA GEÇERSİZ KILAR. ESKİ ANAHTARI KULLANAN TÜM UYGULAMALARIN BAĞLANTISI KESİLECEKTİR.',
      cancel: 'İPTAL ET',
      confirm: 'SIFIRLA',
    },
    service: {
      title: 'SİSTEM DURUMU',
      description: 'YEREL API PROXY SUNUCUSUNU KONTROL ET.',
      running: 'AKTİF',
      stopped: 'ÇEVRİMDIŞI',
      start: 'SERVİSİ BAŞLAT',
      stop: 'SERVİSİ DURDUR',
    },
    config: {
      port: 'DİNLEME PORTU',
      timeout: 'İSTEK ZAMAN AŞIMI',
      api_key: 'GÜVENLİK ANAHTARI (API KEY)',
      auto_start: 'SİSTEMLE OTOMATİK BAŞLAT',
      auto_start_desc: 'UYGULAMA ÇALIŞTIĞINDA PROXY SERVİSİNİ OTOMATİK TETİKLE',
      local_access: 'YEREL AĞ ERİŞİMİ:',
      select_ip: 'IP SEÇİMİ',
      no_token_warning: '⚠️ API ANAHTARI AYARLANMADI. SİSTEM HERKESE AÇIK DURUMDA!',
      show_key: 'GÖSTER',
      hide_key: 'GİZLE',
    },
    mapping: {
      title: 'MODEL YÖNLENDİRME HARİTASI',
      description: 'CLAUDE MODELLERİNİ YÖNLENDİRME İÇİN GEMINI MODELLERİNE BAĞLA.',
      maps_to: 'YÖNLENDİRİLEN:',
      restore: 'VARSAYILANLARA SIFIRLA',
    },
    examples: {
      title: 'KULLANIM PROTOKOLLERİ',
      description: 'YEREL API PROXY İÇİN ÖRNEK ÇAĞRI KOMUTLARI.',
    },
  },
};
